apps/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'apps'
urlpatterns = [

    path('home.html/', views.home, name='home'),
    path('etudiants.html/', views.Etudiants.as_view(), name='etudiants'),
    path('infos-etudiants.html/<int:pk>/', views.details_etudiants, name='details-etudiants'),

    path('badges.html/', views.Badges.as_view(), name='badges'),
    path('details_badges.html/<int:pk>/', views.details_badges, name='details_badges'),
    path('search-badges.html/', views.SearchBadge.as_view(), name='search-badges'),

    path('modifier-infos-etudiants.html/<int:pk>/', views.ModifierEtudiants.as_view(), name='modifier-etudiants'),
    path('changer-photo-etudiants.html/<int:pk>/', views.ChangerPhotoEtudiants.as_view(), name='changer-photo'),
    path('supprimer-etudiants.html/<int:pk>/', views.SupprimerEtudiant.as_view(), name='supprimer-etudiants'),

    path('enseignants.html/', views.Enseignants.as_view(), name='enseignants'),
    path('infos-enseignants.html/<int:pk>/', views.details_enseignants, name='details-enseignants'),
    path('changer-photo-enseignants.html/<int:pk>/', views.ChangerPhotoEnseignants.as_view(),
         name='changer-photo-enseignants'),
    path('modifier-infos-enseignants.html/<int:pk>/', views.ModifierEnseignants.as_view(), name='modifier-enseignants'),

    path('supprimer-enseignants.html/<int:pk>/', views.SupprimerEnseignants.as_view(), name='supprimer-enseignants'),

    path('comptabilite.html/', views.Comptabilite.as_view(), name='comptabilite'),

    path('scolarite.html/', views.Scolarites.as_view(), name='scolarites'),
    path('details-paiements.html/<int:pk>/', views.details_paiements, name='details-paiements'),
    path('effectuer-paiements.html/', views.Paiements.as_view(), name='effectuer-paiements'),
    path('modifier-paiements.html/<int:pk>/', views.ModifierPaiements.as_view(), name='modifier-paiements'),
    path('supprimer-paiements.html/<int:pk>/', views.SupprimerPaiements.as_view(), name='supprimer-paiements'),
    path('recu-paiements.html/<int:pk>/', views.RecuPaiements.as_view(), name='recu-paiements'),

    path('salaires.html/', views.salaires, name='salaires'),
    path('ajouter-salaires.html/', views.AjouterSalaires.as_view(), name='ajouter-salaires'),
    path('modifier-salaires.html/<int:pk>/', views.ModifierSalaires.as_view(), name='modifier-salaires'),
    path('supprimer-salaires.html/<int:pk>/', views.SupprimerSalaires.as_view(), name='supprimer-salaires'),
    path('imprimer-salaires.html/<int:pk>/', views.ImprimerSalaires.as_view(), name='imprimer-salaires'),

    path('charges.html/', views.charges, name='charges'),
    path('ajouter-charges.html/', views.AjouterCharges.as_view(), name='ajouter-charges'),
    path('modifier-charges.html/<int:pk>/', views.ModifierCharges.as_view(), name='modifier-charges'),
    path('supprimer-charges.html/<int:pk>/', views.SupprimerCharge.as_view(), name='supprimer-charges'),

    path('statistiques.html/', views.statistiques, name='statistiques'),

    path('inscriptions.html/', views.inscriptions, name='inscriptions'),
    path('details-inscriptions.html/<int:pk>/', views.details_inscriptions, name='details-inscriptions'),
    path('ajouter-inscription.html/', views.AjouterInscriptions.as_view(), name='ajouter-inscriptions'),
    path('modifier-inscription.html/<int:pk>/', views.ModifierInscriptions.as_view(), name='modifier-inscriptions'),
    path('supprimer-inscription.html/<int:pk>/', views.SupprimerInscription.as_view(), name='supprimer-inscriptions'),

    path('search-etudiants.html/', views.SearchEtudiant.as_view(), name='search-etudiants'),
    path('search-inscriptions.html/', views.SearchInscription.as_view(), name='search-inscriptions'),
    path('search-paiements.html/', views.SearchPaiements.as_view(), name='search-paiements'),
    path('search-enseignants.html/', views.SearchEnseignant.as_view(), name='search-enseignants'),

    path('configurations.html/', views.Configurations.as_view(), name='configurations'),
    path('configurer-etablissement.html/<int:pk>/', views.ConfigurerEtablssement.as_view(),
         name='configurer-etablissement'),
    path('rentree-scolaire.html/', views.RentreeScolaire.as_view(), name='rentree-scolaire'),
    path('infos-rentree-scolaire.html/<int:pk>/', views.InfosRentreeScolaire.as_view(), name='infos-rentree-scolaire'),
    path('ajouter-rentree-scolaire.html/', views.AjouterRentreeScolaire.as_view(), name='ajouter-rentree-scolaire'),
    path('supprimer-rentree-scolaire.html/<int:pk>/', views.SupprimerRentreeScolaire.as_view(),
         name='supprimer-rentree-scolaire'),

    path('matieres.html/', views.Matieres.as_view(), name='matieres'),
    path('ajouter-matiere.html/', views.AjouterMatieres.as_view(), name='ajouter-matiere'),
    path('modifier-matiere.html/<int:pk>/', views.ModifierMatieres.as_view(), name='modifier-matiere'),
    path('supprimer-matiere.html/<int:pk>/', views.SupprimerMatiere.as_view(), name='supprimer-matiere'),

    path('classes.html/', views.Classes.as_view(), name='classes'),
    path('ajouter-classe.html/', views.AjouterClasse.as_view(), name='ajouter-classe'),
    path('modifier-classe.html/<int:pk>/', views.ModifierClasse.as_view(), name='modifier-classe'),
    path('supprimer-classe.html/<int:pk>/', views.SupprimerClasse.as_view(), name='supprimer-classe'),

    path('utilisateurs.html/', views.Utilisateurs.as_view(), name='utilisateurs'),

    path('', auth_views.LoginView.as_view(template_name='admin/login_page.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='admin/logout_page.html'), name='logout'),

]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls')),

    # url(r'^medias/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "apps.views.erreur_404"

users/urls.py
from django.urls import path, re_path
from . import views

app_name = 'users'
urlpatterns = [
    path('register/', views.creer_users, name='creer-users'),
    path('modifier-users.html/<int:pk>/', views.ModifierUsers.as_view(), name='modifier-users'),
    path('supprimer-users.html/<int:pk>/', views.SupprimerUsers.as_view(), name='supprimer-users'),

]

apps/templates/includes/menu.html
            {% load static %}
            <div id="cadre-admin">
                <img src="{% static 'apps/img/user.png' %}">


                {% if user.is_superuser %}

               <span> {{ user.username }}</span>

                    {% else %}




                {% endif  %}

            </div>

              <h1>
                    <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pc-display-horizontal" viewBox="0 0 16 16"><path d="M1.5 0A1.5 1.5 0 0 0 0 1.5v7A1.5 1.5 0 0 0 1.5 10H6v1H1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1h-5v-1h4.5A1.5 1.5 0 0 0 16 8.5v-7A1.5 1.5 0 0 0 14.5 0h-13Zm0 1h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5ZM12 12.5a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0Zm2 0a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0ZM1.5 12h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1ZM1 14.25a.25.25 0 0 1 .25-.25h5.5a.25.25 0 1 1 0 .5h-5.5a.25.25 0 0 1-.25-.25Z"/></svg></span>
                   <span style="margin-left: 5px">Tableau de bord</span>
              </h1>

             <nav id="cadre1">



                  <li>
                      <img src="{% static 'apps/img/etudiant.png' %}">
                     <a  href="{% url 'apps:etudiants' %}">Étudiants</a>

                       <span>({{ etudiants.count }})</span>
                 </li>

                   <li> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16"><path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/></svg>
                       <a  href="{% url 'apps:inscriptions' %}">  Inscriptions </a>

                        {% if annee or classe %}
                        <span>({{ inscriptions_slug.count }})</span>

                           {% else %}
                           <span>({{ inscriptions.count }})</span>

                       {% endif  %}
                   </li>



                 <li>
                     <img src="{% static 'apps/img/badge.png' %}">
                     <a   href="{% url 'apps:badges' %}"> Badges</a>

                     <span>({{ etudiants.count }})</span>


                 </li>


                  <li>
                    <img src="{% static 'apps/img/enseignant.png' %}">
                     <a  href="{% url 'apps:enseignants' %}">Enseignants</a>
                      <span>({{ enseignants.count }})</span>
                 </li>


                 <li>
                    <img src="{% static 'apps/img/comptabilite.png' %}">
                     <a  href="{% url 'apps:comptabilite' %}">Comptabilité</a>
                 </li>

                 <li>
                    <img src="{% static 'apps/img/parametres.png' %}">
                     <a  href="{% url 'apps:configurations' %}">Configurations</a>
                 </li>


             </nav>






{% if user.is_authenticated %}

<li id="home"> <a style="font-weight:bold " href="{% url 'apps:logout' %}">
    <svg style="margin-top: -3px" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
    <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
   </svg>

    <span> Déconnexion </span>

</a>
</li>
{% endif %}

apps/templates/includes/menu2.html
            {% load static %}
            <div id="cadre-admin">
                <img src="{% static 'apps/img/user.png' %}">


                {% if user.is_superuser %}

               <span> {{ user.username }}</span>

                    {% else %}




                {% endif  %}

            </div>

              <h1>
                    <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pc-display-horizontal" viewBox="0 0 16 16"><path d="M1.5 0A1.5 1.5 0 0 0 0 1.5v7A1.5 1.5 0 0 0 1.5 10H6v1H1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1h-5v-1h4.5A1.5 1.5 0 0 0 16 8.5v-7A1.5 1.5 0 0 0 14.5 0h-13Zm0 1h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5ZM12 12.5a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0Zm2 0a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0ZM1.5 12h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1ZM1 14.25a.25.25 0 0 1 .25-.25h5.5a.25.25 0 1 1 0 .5h-5.5a.25.25 0 0 1-.25-.25Z"/></svg></span>
                   <span style="margin-left: 5px">Tableau de bord</span>
              </h1>

             <nav id="cadre1">



                  <li>
                      <img src="{% static 'apps/img/etudiant.png' %}">
                     <a  href="{% url 'apps:etudiants' %}">Étudiants</a>

                       <span>({{ etudiants.count }})</span>
                 </li>

                   <li> <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16"><path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/></svg>
                       <a  href="{% url 'apps:inscriptions' %}">  Inscriptions </a>

                        {% if annee or classe %}
                        <span>({{ inscriptions_slug.count }})</span>

                           {% else %}
                           <span>({{ inscriptions.count }})</span>

                       {% endif  %}
                   </li>



                 <li>
                     <img src="{% static 'apps/img/badge.png' %}">
                     <a   href="{% url 'apps:badges' %}"> Badges</a>

                     <span>({{ etudiants.count }})</span>


                 </li>


                  <li>
                    <img src="{% static 'apps/img/enseignant.png' %}">
                     <a  href="{% url 'apps:enseignants' %}">Enseignants</a>
                      <span>({{ enseignants.count }})</span>
                 </li>


                 <li>
                    <img src="{% static 'apps/img/comptabilite.png' %}">
                     <a  href="{% url 'apps:comptabilite' %}">Comptabilité</a>
                 </li>

                 <li>
                    <img src="{% static 'apps/img/parametres.png' %}">
                     <a  href="{% url 'apps:configurations' %}">Configurations</a>
                 </li>


             </nav>






{% if user.is_authenticated %}

<li id="home"> <a style="font-weight:bold " href="{% url 'apps:logout' %}">
    <svg style="margin-top: -3px" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-left" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M6 12.5a.5.5 0 0 0 .5.5h8a.5.5 0 0 0 .5-.5v-9a.5.5 0 0 0-.5-.5h-8a.5.5 0 0 0-.5.5v2a.5.5 0 0 1-1 0v-2A1.5 1.5 0 0 1 6.5 2h8A1.5 1.5 0 0 1 16 3.5v9a1.5 1.5 0 0 1-1.5 1.5h-8A1.5 1.5 0 0 1 5 12.5v-2a.5.5 0 0 1 1 0v2z"/>
    <path fill-rule="evenodd" d="M.146 8.354a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L1.707 7.5H10.5a.5.5 0 0 1 0 1H1.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3z"/>
   </svg>

    <span> Déconnexion </span>

</a>
</li>
{% endif %}

apps/templates/includes/menu_comptabilite.html
{% load static %}
<div id="cadre-admin">
    <img src="{% static 'apps/img/user.png' %}">


    {% if user.is_superuser %}

        <span> {{ user.username }}</span>

    {% else %}




    {% endif %}

</div>

<h1>
    <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
               class="bi bi-pc-display-horizontal" viewBox="0 0 16 16"><path
            d="M1.5 0A1.5 1.5 0 0 0 0 1.5v7A1.5 1.5 0 0 0 1.5 10H6v1H1a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h14a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1h-5v-1h4.5A1.5 1.5 0 0 0 16 8.5v-7A1.5 1.5 0 0 0 14.5 0h-13Zm0 1h13a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-7a.5.5 0 0 1 .5-.5ZM12 12.5a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0Zm2 0a.5.5 0 1 1 1 0 .5.5 0 0 1-1 0ZM1.5 12h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1ZM1 14.25a.25.25 0 0 1 .25-.25h5.5a.25.25 0 1 1 0 .5h-5.5a.25.25 0 0 1-.25-.25Z"/></svg></span>
    <span style="margin-left: 5px">Tableau de bord</span>
</h1>

<nav id="cadre1">


    <li>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cash-coin"
             viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/>
            <path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/>
            <path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/>
            <path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/>
        </svg>

        <a href="{% url 'apps:scolarites' %}">Scolarités</a>
    </li>

    <li>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cash-stack"
             viewBox="0 0 16 16">
            <path d="M1 3a1 1 0 0 1 1-1h12a1 1 0 0 1 1 1H1zm7 8a2 2 0 1 0 0-4 2 2 0 0 0 0 4z"/>
            <path d="M0 5a1 1 0 0 1 1-1h14a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1H1a1 1 0 0 1-1-1V5zm3 0a2 2 0 0 1-2 2v4a2 2 0 0 1 2 2h10a2 2 0 0 1 2-2V7a2 2 0 0 1-2-2H3z"/>
        </svg>


        <a href="{% url 'apps:salaires' %}">Salaires</a>
    </li>

    <li>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor"
             class="bi bi-arrow-left-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                  d="M1 11.5a.5.5 0 0 0 .5.5h11.793l-3.147 3.146a.5.5 0 0 0 .708.708l4-4a.5.5 0 0 0 0-.708l-4-4a.5.5 0 0 0-.708.708L13.293 11H1.5a.5.5 0 0 0-.5.5zm14-7a.5.5 0 0 1-.5.5H2.707l3.147 3.146a.5.5 0 1 1-.708.708l-4-4a.5.5 0 0 1 0-.708l4-4a.5.5 0 1 1 .708.708L2.707 4H14.5a.5.5 0 0 1 .5.5z"/>
        </svg>

        <a href="{% url 'apps:charges' %}">Charges</a>
    </li>

    <li>
        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrows-move"
             viewBox="0 0 16 16">
            <path fill-rule="evenodd"
                  d="M7.646.146a.5.5 0 0 1 .708 0l2 2a.5.5 0 0 1-.708.708L8.5 1.707V5.5a.5.5 0 0 1-1 0V1.707L6.354 2.854a.5.5 0 1 1-.708-.708l2-2zM8 10a.5.5 0 0 1 .5.5v3.793l1.146-1.147a.5.5 0 0 1 .708.708l-2 2a.5.5 0 0 1-.708 0l-2-2a.5.5 0 0 1 .708-.708L7.5 14.293V10.5A.5.5 0 0 1 8 10zM.146 8.354a.5.5 0 0 1 0-.708l2-2a.5.5 0 1 1 .708.708L1.707 7.5H5.5a.5.5 0 0 1 0 1H1.707l1.147 1.146a.5.5 0 0 1-.708.708l-2-2zM10 8a.5.5 0 0 1 .5-.5h3.793l-1.147-1.146a.5.5 0 0 1 .708-.708l2 2a.5.5 0 0 1 0 .708l-2 2a.5.5 0 0 1-.708-.708L14.293 8.5H10.5A.5.5 0 0 1 10 8z"/>
        </svg>
        

        <a href="{% url 'apps:statistiques' %}">Statistiques</a>
    </li>


</nav>


<li id="home"><a style="font-weight:bold " href="{% url 'apps:home' %}">
    <svg style="margin-top: -5px" xmlns="http://www.w3.org/2000/svg" width="25" height="25" fill="currentColor"
         class="bi bi-list"
         viewBox="0 0 16 16">
        <path fill-rule="evenodd"
              d="M2.5 12a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5zm0-4a.5.5 0 0 1 .5-.5h10a.5.5 0 0 1 0 1H3a.5.5 0 0 1-.5-.5z"/>
    </svg>
    <span> MENU </span>

</a>
</li>

apps/templates/includes/menu_configuration.html
{% load static %}


        <h1 style="font-weight: bold">CONFIGURATIONS</h1>

                 <div id="menu-etablissement" >



                         <li>
                             <span><img src="{% static 'apps/img/etablissement.png' %}"></span>
                             {% for etablissement in  etablissements %}

                             <a href="{% url 'apps:configurer-etablissement' etablissement.id %}">Établissement</a>



                             {% endfor %}
                         </li>

                         <li>
                              <span><img src="{% static 'apps/img/annee.png' %}"></span>
                             <a href="{% url 'apps:rentree-scolaire' %}">Rentrée Scolaire</a>
                         </li>

                         <li>
                              <span><img src="{% static 'apps/img/matiere.png' %}"></span>
                             <a href="{% url 'apps:matieres' %}">Matières</a>
                         </li>

                         <li>
                              <span><img src="{% static 'apps/img/classe.png' %}"></span>
                             <a href="{% url 'apps:classes' %}">Classes</a>
                         </li>



                       {% if user.is_superuser %}
                         <li>
                              <span><img src="{% static 'apps/img/user.png' %}"></span>
                             <a href="{% url 'apps:utilisateurs' %}">Utilisateurs</a>
                         </li>

                         {% else %}

                           <li>
                              <span><img src="{% static 'apps/img/user.png' %}"></span>
                              <a href="">Utilisateurs</a>
                         </li>



                  {% endif  %}





                 </div>

apps/templates/includes/menu_element_configuration.html
{% load static %}


        <h1 style="font-weight: bold">CONFIGURATIONS</h1>

                 <div id="menu-etablissement" >



                         <li>
                             <span><img src="{% static 'apps/img/etablissement.png' %}"></span>
                             {% for etablissement in  etablissements %}

                             <a href="{% url 'apps:configurer-etablissement' etablissement.id %}">Établissement</a>



                             {% endfor %}
                         </li>

                         <li>
                              <span><img src="{% static 'apps/img/annee.png' %}"></span>
                             <a href="{% url 'apps:rentree-scolaire' %}">Rentrée Scolaire</a>
                         </li>

                         <li>
                              <span><img src="{% static 'apps/img/matiere.png' %}"></span>
                             <a href="{% url 'apps:matieres' %}">Matières</a>
                         </li>

                         <li>
                              <span><img src="{% static 'apps/img/classe.png' %}"></span>
                             <a href="{% url 'apps:classes' %}">Classes</a>
                         </li>



                       {% if user.is_superuser %}
                         <li>
                              <span><img src="{% static 'apps/img/user.png' %}"></span>
                             <a href="{% url 'apps:utilisateurs' %}">Utilisateurs</a>
                         </li>

                         {% else %}

                           <li>
                              <span><img src="{% static 'apps/img/user.png' %}"></span>
                              <a href="">Utilisateurs</a>
                         </li>



                  {% endif  %}





                 </div>

apps/templates/includes/messages.html
{% load static %}


                    {% if messages %}
  <div  id="cadre-message"  class="alert alert-success" role="alert">


      {% for message in messages %}

         {{ message }}
              <button type="button" class="close" aria-label="Close">
               <span aria-hidden="true">&times;</span>
               </button>

      {% endfor %}



</div>
   {% endif %}