apps/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'apps'
urlpatterns = [

    path('home.html/', views.home, name='home'),
    path('etudiants.html/', views.Etudiants.as_view(), name='etudiants'),
    path('infos-etudiants.html/<int:pk>/', views.details_etudiants, name='details-etudiants'),

    path('badges.html/', views.Badges.as_view(), name='badges'),
    path('details_badges.html/<int:pk>/', views.details_badges, name='details_badges'),
    path('search-badges.html/', views.SearchBadge.as_view(), name='search-badges'),

    path('modifier-infos-etudiants.html/<int:pk>/', views.ModifierEtudiants.as_view(), name='modifier-etudiants'),
    path('changer-photo-etudiants.html/<int:pk>/', views.ChangerPhotoEtudiants.as_view(), name='changer-photo'),
    path('supprimer-etudiants.html/<int:pk>/', views.SupprimerEtudiant.as_view(), name='supprimer-etudiants'),

    path('enseignants.html/', views.Enseignants.as_view(), name='enseignants'),
    path('infos-enseignants.html/<int:pk>/', views.details_enseignants, name='details-enseignants'),
    path('changer-photo-enseignants.html/<int:pk>/', views.ChangerPhotoEnseignants.as_view(),
         name='changer-photo-enseignants'),
    path('modifier-infos-enseignants.html/<int:pk>/', views.ModifierEnseignants.as_view(), name='modifier-enseignants'),

    path('supprimer-enseignants.html/<int:pk>/', views.SupprimerEnseignants.as_view(), name='supprimer-enseignants'),

    path('comptabilite.html/', views.Comptabilite.as_view(), name='comptabilite'),

    path('scolarite.html/', views.Scolarites.as_view(), name='scolarites'),
    path('details-paiements.html/<int:pk>/', views.details_paiements, name='details-paiements'),
    path('effectuer-paiements.html/', views.Paiements.as_view(), name='effectuer-paiements'),
    path('modifier-paiements.html/<int:pk>/', views.ModifierPaiements.as_view(), name='modifier-paiements'),
    path('supprimer-paiements.html/<int:pk>/', views.SupprimerPaiements.as_view(), name='supprimer-paiements'),
    path('recu-paiements.html/<int:pk>/', views.RecuPaiements.as_view(), name='recu-paiements'),

    path('salaires.html/', views.salaires, name='salaires'),
    path('ajouter-salaires.html/', views.AjouterSalaires.as_view(), name='ajouter-salaires'),
    path('modifier-salaires.html/<int:pk>/', views.ModifierSalaires.as_view(), name='modifier-salaires'),
    path('supprimer-salaires.html/<int:pk>/', views.SupprimerSalaires.as_view(), name='supprimer-salaires'),
    path('imprimer-salaires.html/<int:pk>/', views.ImprimerSalaires.as_view(), name='imprimer-salaires'),

    path('charges.html/', views.charges, name='charges'),
    path('ajouter-charges.html/', views.AjouterCharges.as_view(), name='ajouter-charges'),
    path('modifier-charges.html/<int:pk>/', views.ModifierCharges.as_view(), name='modifier-charges'),
    path('supprimer-charges.html/<int:pk>/', views.SupprimerCharge.as_view(), name='supprimer-charges'),

    path('statistiques.html/', views.statistiques, name='statistiques'),

    path('inscriptions.html/', views.inscriptions, name='inscriptions'),
    path('details-inscriptions.html/<int:pk>/', views.details_inscriptions, name='details-inscriptions'),
    path('ajouter-inscription.html/', views.AjouterInscriptions.as_view(), name='ajouter-inscriptions'),
    path('modifier-inscription.html/<int:pk>/', views.ModifierInscriptions.as_view(), name='modifier-inscriptions'),
    path('supprimer-inscription.html/<int:pk>/', views.SupprimerInscription.as_view(), name='supprimer-inscriptions'),

    path('search-etudiants.html/', views.SearchEtudiant.as_view(), name='search-etudiants'),
    path('search-inscriptions.html/', views.SearchInscription.as_view(), name='search-inscriptions'),
    path('search-paiements.html/', views.SearchPaiements.as_view(), name='search-paiements'),
    path('search-enseignants.html/', views.SearchEnseignant.as_view(), name='search-enseignants'),

    path('configurations.html/', views.Configurations.as_view(), name='configurations'),
    path('configurer-etablissement.html/<int:pk>/', views.ConfigurerEtablssement.as_view(),
         name='configurer-etablissement'),
    path('rentree-scolaire.html/', views.RentreeScolaire.as_view(), name='rentree-scolaire'),
    path('infos-rentree-scolaire.html/<int:pk>/', views.InfosRentreeScolaire.as_view(), name='infos-rentree-scolaire'),
    path('ajouter-rentree-scolaire.html/', views.AjouterRentreeScolaire.as_view(), name='ajouter-rentree-scolaire'),
    path('supprimer-rentree-scolaire.html/<int:pk>/', views.SupprimerRentreeScolaire.as_view(),
         name='supprimer-rentree-scolaire'),

    path('matieres.html/', views.Matieres.as_view(), name='matieres'),
    path('ajouter-matiere.html/', views.AjouterMatieres.as_view(), name='ajouter-matiere'),
    path('modifier-matiere.html/<int:pk>/', views.ModifierMatieres.as_view(), name='modifier-matiere'),
    path('supprimer-matiere.html/<int:pk>/', views.SupprimerMatiere.as_view(), name='supprimer-matiere'),

    path('classes.html/', views.Classes.as_view(), name='classes'),
    path('ajouter-classe.html/', views.AjouterClasse.as_view(), name='ajouter-classe'),
    path('modifier-classe.html/<int:pk>/', views.ModifierClasse.as_view(), name='modifier-classe'),
    path('supprimer-classe.html/<int:pk>/', views.SupprimerClasse.as_view(), name='supprimer-classe'),

    path('utilisateurs.html/', views.Utilisateurs.as_view(), name='utilisateurs'),

    path('', auth_views.LoginView.as_view(template_name='admin/login_page.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='admin/logout_page.html'), name='logout'),

]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls')),

    # url(r'^medias/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "apps.views.erreur_404"

apps/templates/comptabilites/ajouter_charges.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">




        <div id="menu-etudiants">

              {% include 'includes/menu_comptabilite.html' %}


        </div>


        <div id="infos-etudiants">

        <br>



            <div id="cadre">




                <br>

               <div id="cadre-form">

                    <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:charges' %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>

                             <h1 id="titre-enregistrer">
                                 <span>+</span> Ajouter une nouvelle charge
                             </h1><br>

                <form style="" id="form" method="post" enctype="multipart/form-data">

                                {% csrf_token %}
                                {{ form|crispy }}

                                <br><br>

                                <div class="form-group" style="margin: 10px; text-align: center">

                                    <button  class="btn btn-danger" type="submit">Enregistrer la charge</button>

                                </div>
                                <br><br>


                            </form>



               </div>



            </div>


        </div>










    </div>







    </div>





{% endblock body %}

apps/templates/comptabilites/details_paiements.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load django_template_maths %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

              {% include 'includes/menu_comptabilite.html' %}


        </div>


        <div id="infos-etudiants" >


             <br>
            <div id="cadre" style="height: 82vh;">
              <br>

             <div id="menu-comptabilite">


                    {% include 'includes/menu_scolarite.html' %}


            </div>






                <div style="" id="cadre-comptabilite" >

                {% include 'includes/messages.html' %}

                    <div id="photo">

                        {% if inscrit.etudiant.photo %}

                            <img  src="{{  inscrit.etudiant.photo.url }}"/>

                        {% else %}

                            <img src="{% static 'apps/img/user.png' %}"/>

                        {% endif %}


                    </div>

                    <div id="infos">

                        <div id="details" style="height: 290px;" >
                               <h1 style="text-align: center; margin-top: 10px; font-size: 25px; color: grey"> ANNÉE SCOLAIRE : <span style="color: red; font-weight: bold"> {{  inscrit.annee  }}</span></h1> <br>

                         <div id="c1">

                            <h5> Matricule: <span style="color: red; font-weight: bold"> {{  inscrit.etudiant.matricule  }}</span></h5>
                            <h5> Nom: <span>{{  inscrit.etudiant.nom  }}</span></h5>
                            <h5> Prénom: <span>{{  inscrit.etudiant.prenom  }}</span></h5>

                                {% for inscription in inscriptions %}

                                     {% if inscrit.id == inscription.id  %}

                                    <h5> Classe: <span style="color: red; font-weight: bold">{{ inscrit.classe.classe }}</span></h5>


                                     {% endif%}




                                 {% endfor%}

                            <h5> Numéro: <span>{{ inscrit.etudiant.numero  }}</span></h5>


                             {% for inscription in inscriptions %}

                                 {% if  inscription.id == inscrit.id  %}

                                        <h5> Date d'inscription: <span style="color: red; background-color: yellow">{{ inscrit.date }}</span></h5>



                                {% endif%}

                          {% endfor%}


                          </div>

                          <div id="c2">

                            <h5> Date de naissance: <span>{{ inscrit.etudiant.naissance  }}</span></h5>
                            <h5> Lieu de naissance: <span>{{ inscrit.etudiant.lieu  }}</span></h5>
                            <h5> Nom du père: <span>{{ inscrit.etudiant.pere  }}</span></h5>
                            <h5> Nom de la mère: <span>{{ inscrit.etudiant.mere  }}</span></h5>
                            <h5> Numéro d'urgence: <span>{{ inscrit.etudiant.urgent  }}</span></h5>

                           {% for inscription in inscriptions %}

                                 {% if  inscription.id == inscrit.id  %}

                                  <h5> Scolarité: <span style="color: red; font-weight: bold; background-color: yellow">{{ inscrit.scolarite }} GNF</span></h5>

                                {% endif%}

                          {% endfor%}

                          </div>


                        </div>




                    </div>


                <div id="cadre-paiement"  >



                            <div id="detail-payement" >

                             <h1 style=" font-size: 20px; text-align: center; margin-top: 20px">DÉTAILS DES PAIEMENTS</h1>


                <table class="table" id="table-payement" style="margin-top: 0px">

                            <thead >
                            <tr id="tete-table" style="background-color: gray; box-shadow: none">
                                <th scope="col">Dates</th>
                                <th scope="col">Montants</th>
                                <th scope="col">Années</th>
                                <th scope="col">Reçus</th>
                                 <th scope="col">Actions</th>

                            </tr>
                            </thead>

                       <tbody>
                        {% for payement in  scolarites %}



                            {% if payement.etudiant.id == inscrit.id %}

                              <tr>

                                  <td style=""> {{ payement.date }}  </td>
                                  <td  style=""> {{ payement.payement }}  GNF  </td>
                                  <td  style="color: red"> {{ payement.annee }} </td>
                                   <td> <a href="{% url 'apps:recu-paiements' payement.id %}"> Afficher</a></td>
                                  <td>

                                       <span>

                                           <a href="{% url 'apps:modifier-paiements' payement.id %}">
                                             <svg style="margin-top: 2px" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                               <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/><path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                            </svg>
                                           </a>

                                       </span>


                                       <span>

                                           <a href="{% url 'apps:supprimer-paiements' payement.id %}">


                                            <svg style="color: red" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                               <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                                            </svg>

                                           </a>

                                       </span>


                                  </td>


                              </tr>

                            {% endif  %}





                        {% endfor  %}



                       <tbody>


                        </table>


                        <div id="total" style=""> <span id="st1"> TOTAL : </span>

                             {% if total_payement.payement__sum %}

                              <span id="st2">{{ total_payement.payement__sum  }} GNF</span>

                              {% else %}

                              <span id="st2">0 GNF</span>


                             {% endif  %}

                        </div><br>

                       </div>



                </div>









             <div id="info-bas-paiements">



                             {% for inscription in inscriptions %}

                                 {% if inscription.id == inscrit.id  %}

                                         {% if total_payement.payement__sum %}

                                           <h2> IMPAYÉ : <span> {{inscrit.scolarite|sub:total_payement.payement__sum}} FG </span> <br>

                                          {% else%}

                                             <h2> IMPAYÉ : <span> {{inscrit.scolarite|sub:0}} FG </span> <br>


                                          {% endif%}

                                         </h2>


                                {% endif%}

                          {% endfor%}


                                   <div id="effectuer-paiement">

                   <a href="{% url 'apps:effectuer-paiements' %}">

                         Effectuer Paiement


                    <span>

                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-arrow-right-short" viewBox="0 0 16 16">
  <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"/>
</svg>
                    </span>


                   </a>

               </div>







             </div><br>




            </div>







        </div>







    </div>









    </div>







{% endblock body %}

apps/templates/comptabilites/modifier_charges.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">




        <div id="menu-etudiants">

              {% include 'includes/menu_comptabilite.html' %}


        </div>


        <div id="infos-etudiants">

        <br>



            <div id="cadre">




                <br>

               <div id="cadre-form">

                    <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:charges' %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>

                             <h1 id="titre-enregistrer">
                                  Modification de la charge - <span style="color: red">{{ object.commentaire }}</span>
                             </h1><br>

                <form style="" id="form" method="post" enctype="multipart/form-data">

                                {% csrf_token %}
                                {{ form|crispy }}

                                <br><br>

                                <div class="form-group" style="margin: 10px; text-align: center">

                                    <button  class="btn btn-danger" type="submit">Modifier</button>

                                </div>
                                <br><br>


                            </form>



               </div>



            </div>


        </div>










    </div>







    </div>





{% endblock body %}

apps/templates/comptabilites/salaires.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}


{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

              {% include 'includes/menu_comptabilite.html' %}


        </div>


        <div id="infos-etudiants">

         {% include 'includes/messages.html' %}

                                    <div class="row" id="row-etudiants">


                            <div class="col-md-9">

                                <div id="classe-form">
                                 <form style="" method='get' >

                                      {{ myFilter.form }}
                                      {{ form|crispy }}


                                    <input type="submit" value="Recherche">

                                </form>
                            </div>
                            </div>


                            <div class="col-md-3" style=" font-size: 12px;">

                        <span id="imprimer" onclick="printDiv5()">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-printer-fill" viewBox="0 0 16 16">
                        <path d="M5 1a2 2 0 0 0-2 2v1h10V3a2 2 0 0 0-2-2H5zm6 8H5a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1z"/>
                        <path d="M0 7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-1v-2a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2H2a2 2 0 0 1-2-2V7zm2.5 1a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1z"/>
                        </svg>
                        </span>

                            </div>

                        </div>

            <div id="cadre" style="height: 75vh;overflow:hidden; margin-top: 10px">


                <table class="table" id="table">

                            <thead>
                            <tr id="tete-table">
                                <th scope="col">Photo</th>
                                <th scope="col">Matricule</th>
                                <th scope="col">Prénom </th>
                                <th scope="col">Nom</th>
                                <th scope="col" style="">Mois</th>
                                <th scope="col" style="">Années</th>
                                <th scope="col" style="">Dates de paiement</th>
                                <th scope="col" style="">Salaire(GNF)</th>
                                <th scope="col">Reçus</th>
                                <th scope="col">Actions</th>

                            </tr>
                            </thead>


                            <tbody>

                            {% for salaire in salaires_filters%}


                                <tr>

                                    <td style=""> {% if salaire.enseignant.photo %}<img style="width: 40px; height: 40px; border-radius: 200px" src="{{ salaire.enseignant.photo.url }}"/> {% else %}<img style="width: 40px; height: 40px" src="{% static 'apps/img/user.png' %}"/>  {% endif %} </td>
                                    <td style="color: red; font-weight: bold"> {{ salaire.enseignant.matricule }}  </td>
                                    <td style="font-weight: bold">{{ salaire.enseignant.prenom }} </td>
                                    <td style="font-weight: bold">{{ salaire.enseignant.nom }}  </td>
                                    <td style="">{{ salaire.mois }}</td>
                                    <td style="">{{ salaire.annee }}</td>
                                    <td >{{ salaire.date }}</td>
                                   <td style=" color: red">{{ salaire.salaire }} GNF</td>

                                    <td style="text-align: center"><a href="{% url 'apps:imprimer-salaires' salaire.id %}" style=" text-decoration: none;">Imprimer</a></td>

                                   <td style="">

                                       <span>

                                           <a href="{% url 'apps:modifier-salaires' salaire.id%}">
                                             <svg style="margin-top: 2px" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                               <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/><path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                            </svg>
                                           </a>

                                       </span>


                                       <span>

                                           <a href="{% url 'apps:supprimer-salaires' salaire.id %}">

                                            <svg style="color: red" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                               <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                                            </svg>

                                           </a>

                                       </span>

                                   </td>


                                </tr>



                            {% endfor %}




                            </tbody>

                </table>


               <div id="imprimer-salaire">{% include 'includes/imprimer_salaire.html' %}</div>








            </div>



                      <div style="width: 95%; margin: auto">

                <span id="ajouter-inscrit">


                    <a style="color: red" href="{% url 'apps:ajouter-salaires' %}">

                        <span><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-cash-coin" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M11 15a4 4 0 1 0 0-8 4 4 0 0 0 0 8zm5-4a5 5 0 1 1-10 0 5 5 0 0 1 10 0z"/><path d="M9.438 11.944c.047.596.518 1.06 1.363 1.116v.44h.375v-.443c.875-.061 1.386-.529 1.386-1.207 0-.618-.39-.936-1.09-1.1l-.296-.07v-1.2c.376.043.614.248.671.532h.658c-.047-.575-.54-1.024-1.329-1.073V8.5h-.375v.45c-.747.073-1.255.522-1.255 1.158 0 .562.378.92 1.007 1.066l.248.061v1.272c-.384-.058-.639-.27-.696-.563h-.668zm1.36-1.354c-.369-.085-.569-.26-.569-.522 0-.294.216-.514.572-.578v1.1h-.003zm.432.746c.449.104.655.272.655.569 0 .339-.257.571-.709.614v-1.195l.054.012z"/><path d="M1 0a1 1 0 0 0-1 1v8a1 1 0 0 0 1 1h4.083c.058-.344.145-.678.258-1H3a2 2 0 0 0-2-2V3a2 2 0 0 0 2-2h10a2 2 0 0 0 2 2v3.528c.38.34.717.728 1 1.154V1a1 1 0 0 0-1-1H1z"/<path d="M9.998 5.083 10 5a2 2 0 1 0-3.132 1.65 5.982 5.982 0 0 1 3.13-1.567z"/></svg></span>
                        Paiement salaire ->

                    </a>


                </span>



          </div>


        </div>










    </div>







    </div>





{% endblock body %}