apps/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'apps'
urlpatterns = [

    path('home.html/', views.home, name='home'),
    path('etudiants.html/', views.Etudiants.as_view(), name='etudiants'),
    path('infos-etudiants.html/<int:pk>/', views.details_etudiants, name='details-etudiants'),

    path('badges.html/', views.Badges.as_view(), name='badges'),
    path('details_badges.html/<int:pk>/', views.details_badges, name='details_badges'),
    path('search-badges.html/', views.SearchBadge.as_view(), name='search-badges'),

    path('modifier-infos-etudiants.html/<int:pk>/', views.ModifierEtudiants.as_view(), name='modifier-etudiants'),
    path('changer-photo-etudiants.html/<int:pk>/', views.ChangerPhotoEtudiants.as_view(), name='changer-photo'),
    path('supprimer-etudiants.html/<int:pk>/', views.SupprimerEtudiant.as_view(), name='supprimer-etudiants'),

    path('enseignants.html/', views.Enseignants.as_view(), name='enseignants'),
    path('infos-enseignants.html/<int:pk>/', views.details_enseignants, name='details-enseignants'),
    path('changer-photo-enseignants.html/<int:pk>/', views.ChangerPhotoEnseignants.as_view(),
         name='changer-photo-enseignants'),
    path('modifier-infos-enseignants.html/<int:pk>/', views.ModifierEnseignants.as_view(), name='modifier-enseignants'),

    path('supprimer-enseignants.html/<int:pk>/', views.SupprimerEnseignants.as_view(), name='supprimer-enseignants'),

    path('comptabilite.html/', views.Comptabilite.as_view(), name='comptabilite'),

    path('scolarite.html/', views.Scolarites.as_view(), name='scolarites'),
    path('details-paiements.html/<int:pk>/', views.details_paiements, name='details-paiements'),
    path('effectuer-paiements.html/', views.Paiements.as_view(), name='effectuer-paiements'),
    path('modifier-paiements.html/<int:pk>/', views.ModifierPaiements.as_view(), name='modifier-paiements'),
    path('supprimer-paiements.html/<int:pk>/', views.SupprimerPaiements.as_view(), name='supprimer-paiements'),
    path('recu-paiements.html/<int:pk>/', views.RecuPaiements.as_view(), name='recu-paiements'),

    path('salaires.html/', views.salaires, name='salaires'),
    path('ajouter-salaires.html/', views.AjouterSalaires.as_view(), name='ajouter-salaires'),
    path('modifier-salaires.html/<int:pk>/', views.ModifierSalaires.as_view(), name='modifier-salaires'),
    path('supprimer-salaires.html/<int:pk>/', views.SupprimerSalaires.as_view(), name='supprimer-salaires'),
    path('imprimer-salaires.html/<int:pk>/', views.ImprimerSalaires.as_view(), name='imprimer-salaires'),

    path('charges.html/', views.charges, name='charges'),
    path('ajouter-charges.html/', views.AjouterCharges.as_view(), name='ajouter-charges'),
    path('modifier-charges.html/<int:pk>/', views.ModifierCharges.as_view(), name='modifier-charges'),
    path('supprimer-charges.html/<int:pk>/', views.SupprimerCharge.as_view(), name='supprimer-charges'),

    path('statistiques.html/', views.statistiques, name='statistiques'),

    path('inscriptions.html/', views.inscriptions, name='inscriptions'),
    path('details-inscriptions.html/<int:pk>/', views.details_inscriptions, name='details-inscriptions'),
    path('ajouter-inscription.html/', views.AjouterInscriptions.as_view(), name='ajouter-inscriptions'),
    path('modifier-inscription.html/<int:pk>/', views.ModifierInscriptions.as_view(), name='modifier-inscriptions'),
    path('supprimer-inscription.html/<int:pk>/', views.SupprimerInscription.as_view(), name='supprimer-inscriptions'),

    path('search-etudiants.html/', views.SearchEtudiant.as_view(), name='search-etudiants'),
    path('search-inscriptions.html/', views.SearchInscription.as_view(), name='search-inscriptions'),
    path('search-paiements.html/', views.SearchPaiements.as_view(), name='search-paiements'),
    path('search-enseignants.html/', views.SearchEnseignant.as_view(), name='search-enseignants'),

    path('configurations.html/', views.Configurations.as_view(), name='configurations'),
    path('configurer-etablissement.html/<int:pk>/', views.ConfigurerEtablssement.as_view(),
         name='configurer-etablissement'),
    path('rentree-scolaire.html/', views.RentreeScolaire.as_view(), name='rentree-scolaire'),
    path('infos-rentree-scolaire.html/<int:pk>/', views.InfosRentreeScolaire.as_view(), name='infos-rentree-scolaire'),
    path('ajouter-rentree-scolaire.html/', views.AjouterRentreeScolaire.as_view(), name='ajouter-rentree-scolaire'),
    path('supprimer-rentree-scolaire.html/<int:pk>/', views.SupprimerRentreeScolaire.as_view(),
         name='supprimer-rentree-scolaire'),

    path('matieres.html/', views.Matieres.as_view(), name='matieres'),
    path('ajouter-matiere.html/', views.AjouterMatieres.as_view(), name='ajouter-matiere'),
    path('modifier-matiere.html/<int:pk>/', views.ModifierMatieres.as_view(), name='modifier-matiere'),
    path('supprimer-matiere.html/<int:pk>/', views.SupprimerMatiere.as_view(), name='supprimer-matiere'),

    path('classes.html/', views.Classes.as_view(), name='classes'),
    path('ajouter-classe.html/', views.AjouterClasse.as_view(), name='ajouter-classe'),
    path('modifier-classe.html/<int:pk>/', views.ModifierClasse.as_view(), name='modifier-classe'),
    path('supprimer-classe.html/<int:pk>/', views.SupprimerClasse.as_view(), name='supprimer-classe'),

    path('utilisateurs.html/', views.Utilisateurs.as_view(), name='utilisateurs'),

    path('', auth_views.LoginView.as_view(template_name='admin/login_page.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='admin/logout_page.html'), name='logout'),

]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls')),

    # url(r'^medias/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "apps.views.erreur_404"

apps/templates/apps/badges.html
{% extends 'base.html' %}
{% load static %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">


              <br>
            <div id="cadre" style="height: 82vh;overflow:hidden">






            <br>

             <div id="menu-comptabilite">


                    {% include 'includes/menu_badge.html' %}


            </div>





                <div  id="cadre-badge"  >

                {% include 'includes/messages.html' %}


                    <div id="badge" >

                          <img id="photo-badge" src="{% static 'apps/img/user.png' %}">

                          <h1 id="annee-badge">ETABLISSEMENT</h1>




                        <img id="badge-img" style="width: 340px; height: 220px; border: 2px solid grey; border-radius: 10px; margin: auto;" src="{% static 'apps/img/badge-vierge.png' %}">



                        <h1 id="nom-badge"> -------- -------</h1>
                        <h1 id="naissance-badge"> -- -- ----</h1>

                        <h1 id="matricule-badge"> Matricule : <span style="color: red; font-size: 11px"> --- </span> </h1>




                    </div>





                   </div>






            </div>


        </div>










    </div>







    </div>





{% endblock body %}

apps/templates/apps/details_enseignants.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load django_template_maths %}



{% block body %}
    <div  id="container">


        <div id="menu-etudiants">

           {% include 'includes/menu_enseigants.html' %}


        </div>


        <div id="infos-etudiants">

            <br>


            {% include 'includes/messages.html' %}


            <div id="cadre" style="">








                <div style="" id="cadre-details-infos" >



                    <div id="photo">

                        {% if enseignant.photo %}

                            <img  src="{{ enseignant.photo.url }}"/>

                        {% else %}

                            <img src="{% static 'apps/img/user.png' %}"/>

                        {% endif %}

                      <p><a href="{% url 'apps:changer-photo-enseignants' enseignant.id %}">Changer photo</a></p>

                    </div>

                    <div id="infos" style="">



                        <div id="details" style=" height: 550px">



                            <h1 style="text-align: center; margin-top: 10px; font-size: 25px; color: grey; box-shadow: 2px 2px 2px 2px"> MATRICULE : <span style="color: red; font-weight: bold"> {{ enseignant.matricule  }}</span>


                                <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:enseignants' %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>
                            </h1>

                            <br>

                         <div id="c1">

                            <h5> Nom: <span>{{ enseignant.nom }}</span></h5>
                            <h5> Prénom: <span>{{ enseignant.prenom }}</span></h5>



                          </div>

                          <div id="c2">

                            <h5> Date de naissance: <span>{{ enseignant.naissance  }}</span></h5>
                             <h5> Numéro: <span>{{ enseignant.numero }}</span></h5>



                          </div>


                    <div class="col-md-12" id="matiere-classe">

                        <div class="row" style="width: 100%; margin: auto">

                            <div id="d1" class="col-md-6">
                                <h1>MATIÈRES</h1>

                                {% for matiere in enseignant.matiere.all %}

                                    <span>{{ matiere  }}</span> <br>

                                {% endfor %}



                            </div>

                            <div  id="d1" class="col-md-6" style=" border-left: 1px solid grey;">

                                 <h1>CLASSES</h1>

                                 {% for classe in enseignant.classe.all %}

                                     <span>{{ classe  }}</span> <br>

                                 {% endfor %}



                            </div>


                        </div>


                    </div>


                     <div id="info-bas-enseignant">


                                <li><a class="btn btn-success" href="{% url 'apps:modifier-enseignants' enseignant.id%}">Modifier</a></li>
                                <li><a class="btn btn-danger" href="{% url 'apps:supprimer-enseignants' enseignant.id%}">Supprimer</a></li><br><br>




                            </div>












                        </div>







                    </div>






                </div>
























            </div>





        </div>





    </div>





{% endblock body %}

apps/templates/apps/details_etudiants.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% load django_template_maths %}



{% block body %}
    <div  id="container">


        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">
            <br>


            {% include 'includes/messages.html' %}


            <div id="cadre" style="">


                <div style="" id="cadre-details-infos" >

                    <div id="photo">

                        {% if etudiant.photo %}

                            <img  src="{{ etudiant.photo.url }}"/>

                        {% else %}

                            <img src="{% static 'apps/img/user.png' %}"/>

                        {% endif %}

                      <p><a href="{% url 'apps:changer-photo' etudiant.id %}">Changer photo</a></p>

                    </div>

                    <div id="infos">

                        <div id="details">




                            <h1 style="text-align: center; margin-top: 10px; font-size: 25px; color: grey; box-shadow: 2px 2px 2px 2px"> MATRICULE : <span style="color: red; font-weight: bold"> {{  etudiant.matricule  }}</span>


                                <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:etudiants' %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>
                            </h1>

                         <div id="c1">

                            <h5> Nom: <span>{{ etudiant.nom  }}</span></h5>
                            <h5> Prénom: <span>{{ etudiant.prenom  }}</span></h5>
                            <h5> Numéro: <span>{{ etudiant.numero  }}</span></h5>
                            <h5> Numéro en cas d'urgence: <span>{{ etudiant.urgent  }}</span></h5>


                          </div>

                          <div id="c2">

                            <h5> Date de naissance: <span>{{ etudiant.naissance  }}</span></h5>
                            <h5> Lieu de naissance: <span>{{ etudiant.lieu  }}</span></h5>
                            <h5> Nom du père: <span>{{ etudiant.pere  }}</span></h5>
                            <h5> Nom de la mère: <span>{{ etudiant.mere  }}</span></h5>



                          </div>



                             <div id="info-bas-details">


                                <li><a class="btn btn-success" href="{% url 'apps:modifier-etudiants' etudiant.id%}">Modifier</a></li>
                                <li><a class="btn btn-danger" href="{% url 'apps:supprimer-etudiants' etudiant.id%}">Supprimer</a></li><br><br>



                            </div>








                        </div>





                    </div>



                </div>




            </div>





        </div>





    </div>





{% endblock body %}

apps/templates/apps/home.html
{% extends 'base.html' %}
{% load static %}



{% block body %}
    <div id="container">


        <div id="cadre-home">


            <div id="mini">


                <img src="{% static 'apps/img/etudiant.png' %}"><br><br>

                <a href="{% url 'apps:etudiants' %}">Étudiants <span
                        style="color: red">({{ etudiants.count }})</span></a><br>


            </div>

            <div id="mini">

                <img src="{% static 'apps/img/enseignant.png' %}"><br><br>


                <a href="{% url 'apps:enseignants' %}">Enseignants <span
                        style="color: red">({{ enseignants.count }})</span></a>

            </div>


            <div id="mini">

                <img src="{% static 'apps/img/comptabilite.png' %}"><br><br>


                <a href="{% url 'apps:comptabilite' %}">Comptabilité</a>


            </div>


            <div id="mini">

                <img src="{% static 'apps/img/parametres.png' %}"><br><br>


                <a href="{% url 'apps:configurations' %}">Configuration</a>


            </div>


            <div id="mini">

                <img src="{% static 'apps/img/logout.png' %}"><br><br>


                <a href="{% url 'apps:logout' %}">Déconnexion</a>


            </div>


        </div>


    </div>





{% endblock body %}

apps/templates/apps/inscriptions.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">

        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">

         {% include 'includes/messages.html' %}





                        <div class="row" id="row-etudiants">


                            <div class="col-md-9">

                                <div id="classe-form">
                                 <form style="" method='get' >

                                      {{ myFilter.form }}
                                      {{ form|crispy }}


                                    <input type="submit" value="Recherche">

                                </form>
                            </div>
                            </div>


                            <div class="col-md-3" style=" font-size: 12px;">

                        <span id="imprimer" onclick="printDiv3()">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-printer-fill" viewBox="0 0 16 16">
                        <path d="M5 1a2 2 0 0 0-2 2v1h10V3a2 2 0 0 0-2-2H5zm6 8H5a1 1 0 0 0-1 1v3a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1v-3a1 1 0 0 0-1-1z"/>
                        <path d="M0 7a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v3a2 2 0 0 1-2 2h-1v-2a2 2 0 0 0-2-2H5a2 2 0 0 0-2 2v2H2a2 2 0 0 1-2-2V7zm2.5 1a.5.5 0 1 0 0-1 .5.5 0 0 0 0 1z"/>
                        </svg>
                        </span>

                            </div>

                        </div>






         <div id="cadre-nombre">


                       <h1 id="nombre">  <span style="color: red"> {{ inscriptions_filters.count }} </span> ÉTUDIANTS DEJA <span style="color: red"> INSCRITS </span></h1>



              </div>


            <div id="cadre" style="overflow: hidden">




                <table class="table" id="table">

                            <thead>
                            <tr id="tete-table">
                                <th scope="col">Photo</th>
                                <th scope="col">Matricule</th>
                                <th scope="col">Prénom </th>
                                <th scope="col">Nom</th>
                                <th scope="col" style="">Naissance</th>
                                <th scope="col" style="">Numéro</th>
                                <th scope="col" style="">Classes</th>
                                <th scope="col" style="">Années Scolaire</th>
                                <th scope="col">Détails</th>
                                <th scope="col">Actions</th>

                            </tr>
                            </thead>


                            <tbody>

                            {% for inscription in inscriptions_filters%}


                                <tr>

                                    <td style=""> {% if inscription.etudiant.photo %}<img style="width: 40px; height: 40px; border-radius: 200px" src="{{ inscription.etudiant.photo.url }}"/> {% else %}<img style="width: 40px; height: 40px" src="{% static 'apps/img/user.png' %}"/>  {% endif %} </td>
                                    <td style="color: red; font-weight: bold"> {{ inscription.etudiant.matricule }}  </td>
                                    <td style="font-weight: bold">{{ inscription.etudiant.prenom }} </td>
                                    <td style="font-weight: bold">{{ inscription.etudiant.nom }}  </td>
                                    <td style="">{{ inscription.etudiant.naissance }}</td>
                                    <td style="">{{ inscription.etudiant.numero }}</td>
                                    <td style=" color: red">{{ inscription.classe }}</td>
                                    <td style=" color: red">{{ inscription.annee }}</td>

                                    <td style="text-align: center"><a href="{% url 'apps:details-inscriptions' inscription.id %}" style=" text-decoration: none;">Afficher</a></td>

                                   <td style="">

                                       <span>

                                           <a href="{% url 'apps:modifier-inscriptions' inscription.id%}">
                                             <svg style="margin-top: 2px" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-pencil-square" viewBox="0 0 16 16">
                                               <path d="M15.502 1.94a.5.5 0 0 1 0 .706L14.459 3.69l-2-2L13.502.646a.5.5 0 0 1 .707 0l1.293 1.293zm-1.75 2.456-2-2L4.939 9.21a.5.5 0 0 0-.121.196l-.805 2.414a.25.25 0 0 0 .316.316l2.414-.805a.5.5 0 0 0 .196-.12l6.813-6.814z"/><path fill-rule="evenodd" d="M1 13.5A1.5 1.5 0 0 0 2.5 15h11a1.5 1.5 0 0 0 1.5-1.5v-6a.5.5 0 0 0-1 0v6a.5.5 0 0 1-.5.5h-11a.5.5 0 0 1-.5-.5v-11a.5.5 0 0 1 .5-.5H9a.5.5 0 0 0 0-1H2.5A1.5 1.5 0 0 0 1 2.5v11z"/>
                                            </svg>
                                           </a>

                                       </span>


                                       <span>

                                           <a href="{% url 'apps:supprimer-inscriptions' inscription.id %}">

                                            <svg style="color: red" xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-trash3" viewBox="0 0 16 16">
                                               <path d="M6.5 1h3a.5.5 0 0 1 .5.5v1H6v-1a.5.5 0 0 1 .5-.5ZM11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3A1.5 1.5 0 0 0 5 1.5v1H2.506a.58.58 0 0 0-.01 0H1.5a.5.5 0 0 0 0 1h.538l.853 10.66A2 2 0 0 0 4.885 16h6.23a2 2 0 0 0 1.994-1.84l.853-10.66h.538a.5.5 0 0 0 0-1h-.995a.59.59 0 0 0-.01 0H11Zm1.958 1-.846 10.58a1 1 0 0 1-.997.92h-6.23a1 1 0 0 1-.997-.92L3.042 3.5h9.916Zm-7.487 1a.5.5 0 0 1 .528.47l.5 8.5a.5.5 0 0 1-.998.06L5 5.03a.5.5 0 0 1 .47-.53Zm5.058 0a.5.5 0 0 1 .47.53l-.5 8.5a.5.5 0 1 1-.998-.06l.5-8.5a.5.5 0 0 1 .528-.47ZM8 4.5a.5.5 0 0 1 .5.5v8.5a.5.5 0 0 1-1 0V5a.5.5 0 0 1 .5-.5Z"/>
                                            </svg>

                                           </a>

                                       </span>

                                   </td>


                                </tr>



                            {% endfor %}










                            </tbody>

                </table>


               <div id="imprimer-classe">{% include 'includes/imprimer_inscription.html' %}</div>






            </div>






          <div style="width: 95%; margin: auto">

                <span id="ajouter-inscrit">


                    <a href="{% url 'apps:ajouter-inscriptions' %}">

                        <span><svg style="margin-top: -5px" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16"><path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/></svg></span>

                        Nouvelle inscription

                    </a>


                </span>



          </div>





        </div>













    </div>





{% endblock body %}

apps/templates/apps/search_enseignants.html
{% extends 'base.html' %}
{% load static %}
{% load class_name %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">

                        <div class="row" id="row-etudiants">


                            <div class="col-md-9">
                                <form style="" method='get' action="{% url 'apps:search-enseignants' %}"

                                      class="navbar-form navbar-right" role="search">

                                    <input id="search-form"
                                           style="background-image: url( '{% static 'apps/img/search.png' %}')" name="q"
                                           type="search" minlength="1" placeholder="Nom, Prénom, Matricule, Numéro ."
                                           class="form-control"/>

                                </form>
                            </div>


                            <div class="col-md-3" style="margin-top: 10px; font-size: 12px"><a href="{% url 'apps:ajouter-enseignants' %}" style="float: right">+ Ajouter un nouveau enseignant</a></div>

                        </div>




        <div id="cadre-nombre">

                       <h1 id="nombre">
                            {% if  query == "" %}

                         <span style="color: red"> Veuillez saisir un mot cle dans la bare de recherche .... </span>


                       {% else %}



                        {% if  count > 1 %}


                          <span>  <span style="font-weight: bold; color:red;"> {{ count }}</span>  résultats  trouvés   pour <span style="font-weight: bold; color:red;">{{ query }}</span></span>

                        {% elif  count == 1 %}

                           <span>  <span style="font-weight: bold; color:red;"> {{ count }}</span>    résultat  trouvé   pour <span style="font-weight: bold; color:red;">{{ query }}</span></span>

                          {% elif  count == 0 %}

                           <span>  <span style="font-weight: bold; color:red;"> {{ count }}</span>    résultat  trouvé   pour <span style="font-weight: bold; color:red;">{{ query }}</span></span>
                       {% endif  %}


                 {% endif  %}


                       </h1>

              </div>
            <div id="cadre">



                <table class="table" id="table" >

                            <thead>
                            <tr id="tete-table">
                                <th scope="col">Photo</th>
                                <th scope="col">Matricule</th>
                                <th scope="col">Prénom</th>
                                <th scope="col">Nom</th>
                                <th scope="col" style="">Naissance</th>
                                <th scope="col" style="">Numéro</th>
                                <th scope="col">Détails</th>

                            </tr>
                            </thead>


                            <tbody>


                            {% for enseignant in object_list %}

                                {% with enseignant|class_name as klass %}

                                {% if  query %}

                                <tr>

                                    <td style=""> {% if enseignant.photo %}<img style="width: 40px; height: 40px; border-radius: 200px" src="{{ enseignant.photo.url }}"/> {% else %}<img style="width: 40px; height: 40px" src="{% static 'apps/img/user.png' %}"/>  {% endif %} </td>
                                    <td style="color: red; font-weight: bold"> {{ enseignant.matricule }}  </td>
                                    <td style="font-weight: bold"> {{ enseignant.prenom }}  </td>
                                    <td style="font-weight: bold"> {{ enseignant.nom }} </td>
                                    <td style="">{{ enseignant.naissance }}</td>
                                    <td style="">{{enseignant.numero }}</td>






                                    <td style="text-align: center"><a href="{% url 'apps:details-enseignants' enseignant.id%}" style=" text-decoration: none;">Afficher</a></td>




                                </tr>


                            {% endif %}



                           {% endwith %}

                         {% empty %}
                        {% endfor %}


                            </tbody>

                </table>


            </div>


        </div>










    </div>







    </div>





{% endblock body %}