apps/urls.py
from django.urls import path, re_path
from . import views
from django.contrib.auth import views as auth_views

app_name = 'apps'
urlpatterns = [

    path('home.html/', views.home, name='home'),
    path('etudiants.html/', views.Etudiants.as_view(), name='etudiants'),
    path('infos-etudiants.html/<int:pk>/', views.details_etudiants, name='details-etudiants'),

    path('badges.html/', views.Badges.as_view(), name='badges'),
    path('details_badges.html/<int:pk>/', views.details_badges, name='details_badges'),
    path('search-badges.html/', views.SearchBadge.as_view(), name='search-badges'),

    path('modifier-infos-etudiants.html/<int:pk>/', views.ModifierEtudiants.as_view(), name='modifier-etudiants'),
    path('changer-photo-etudiants.html/<int:pk>/', views.ChangerPhotoEtudiants.as_view(), name='changer-photo'),
    path('supprimer-etudiants.html/<int:pk>/', views.SupprimerEtudiant.as_view(), name='supprimer-etudiants'),

    path('enseignants.html/', views.Enseignants.as_view(), name='enseignants'),
    path('infos-enseignants.html/<int:pk>/', views.details_enseignants, name='details-enseignants'),
    path('changer-photo-enseignants.html/<int:pk>/', views.ChangerPhotoEnseignants.as_view(),
         name='changer-photo-enseignants'),
    path('modifier-infos-enseignants.html/<int:pk>/', views.ModifierEnseignants.as_view(), name='modifier-enseignants'),

    path('supprimer-enseignants.html/<int:pk>/', views.SupprimerEnseignants.as_view(), name='supprimer-enseignants'),

    path('comptabilite.html/', views.Comptabilite.as_view(), name='comptabilite'),

    path('scolarite.html/', views.Scolarites.as_view(), name='scolarites'),
    path('details-paiements.html/<int:pk>/', views.details_paiements, name='details-paiements'),
    path('effectuer-paiements.html/', views.Paiements.as_view(), name='effectuer-paiements'),
    path('modifier-paiements.html/<int:pk>/', views.ModifierPaiements.as_view(), name='modifier-paiements'),
    path('supprimer-paiements.html/<int:pk>/', views.SupprimerPaiements.as_view(), name='supprimer-paiements'),
    path('recu-paiements.html/<int:pk>/', views.RecuPaiements.as_view(), name='recu-paiements'),

    path('salaires.html/', views.salaires, name='salaires'),
    path('ajouter-salaires.html/', views.AjouterSalaires.as_view(), name='ajouter-salaires'),
    path('modifier-salaires.html/<int:pk>/', views.ModifierSalaires.as_view(), name='modifier-salaires'),
    path('supprimer-salaires.html/<int:pk>/', views.SupprimerSalaires.as_view(), name='supprimer-salaires'),
    path('imprimer-salaires.html/<int:pk>/', views.ImprimerSalaires.as_view(), name='imprimer-salaires'),

    path('charges.html/', views.charges, name='charges'),
    path('ajouter-charges.html/', views.AjouterCharges.as_view(), name='ajouter-charges'),
    path('modifier-charges.html/<int:pk>/', views.ModifierCharges.as_view(), name='modifier-charges'),
    path('supprimer-charges.html/<int:pk>/', views.SupprimerCharge.as_view(), name='supprimer-charges'),

    path('statistiques.html/', views.statistiques, name='statistiques'),

    path('inscriptions.html/', views.inscriptions, name='inscriptions'),
    path('details-inscriptions.html/<int:pk>/', views.details_inscriptions, name='details-inscriptions'),
    path('ajouter-inscription.html/', views.AjouterInscriptions.as_view(), name='ajouter-inscriptions'),
    path('modifier-inscription.html/<int:pk>/', views.ModifierInscriptions.as_view(), name='modifier-inscriptions'),
    path('supprimer-inscription.html/<int:pk>/', views.SupprimerInscription.as_view(), name='supprimer-inscriptions'),

    path('search-etudiants.html/', views.SearchEtudiant.as_view(), name='search-etudiants'),
    path('search-inscriptions.html/', views.SearchInscription.as_view(), name='search-inscriptions'),
    path('search-paiements.html/', views.SearchPaiements.as_view(), name='search-paiements'),
    path('search-enseignants.html/', views.SearchEnseignant.as_view(), name='search-enseignants'),

    path('configurations.html/', views.Configurations.as_view(), name='configurations'),
    path('configurer-etablissement.html/<int:pk>/', views.ConfigurerEtablssement.as_view(),
         name='configurer-etablissement'),
    path('rentree-scolaire.html/', views.RentreeScolaire.as_view(), name='rentree-scolaire'),
    path('infos-rentree-scolaire.html/<int:pk>/', views.InfosRentreeScolaire.as_view(), name='infos-rentree-scolaire'),
    path('ajouter-rentree-scolaire.html/', views.AjouterRentreeScolaire.as_view(), name='ajouter-rentree-scolaire'),
    path('supprimer-rentree-scolaire.html/<int:pk>/', views.SupprimerRentreeScolaire.as_view(),
         name='supprimer-rentree-scolaire'),

    path('matieres.html/', views.Matieres.as_view(), name='matieres'),
    path('ajouter-matiere.html/', views.AjouterMatieres.as_view(), name='ajouter-matiere'),
    path('modifier-matiere.html/<int:pk>/', views.ModifierMatieres.as_view(), name='modifier-matiere'),
    path('supprimer-matiere.html/<int:pk>/', views.SupprimerMatiere.as_view(), name='supprimer-matiere'),

    path('classes.html/', views.Classes.as_view(), name='classes'),
    path('ajouter-classe.html/', views.AjouterClasse.as_view(), name='ajouter-classe'),
    path('modifier-classe.html/<int:pk>/', views.ModifierClasse.as_view(), name='modifier-classe'),
    path('supprimer-classe.html/<int:pk>/', views.SupprimerClasse.as_view(), name='supprimer-classe'),

    path('utilisateurs.html/', views.Utilisateurs.as_view(), name='utilisateurs'),

    path('', auth_views.LoginView.as_view(template_name='admin/login_page.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='admin/logout_page.html'), name='logout'),

]

settings/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.urls')),
    path('', include('django.contrib.auth.urls')),
    path('', include('users.urls')),

    # url(r'^medias/(?P<path>.*)$', serve, {'document_root': settings.MEDIA_ROOT}),
    # url(r'^static/(?P<path>.*)$', serve, {'document_root': settings.STATIC_ROOT}),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = "apps.views.erreur_404"

apps/templates/operations/ajouter_inscriptions.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">




        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">

            <br>


            <div id="cadre">




                <br>

               <div id="cadre-form">

                    <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:inscriptions' %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>

                             <h1 id="titre-enregistrer">

                                 <span><svg style="margin-top: -5px" xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-person-plus-fill" viewBox="0 0 16 16"><path d="M1 14s-1 0-1-1 1-4 6-4 6 3 6 4-1 1-1 1H1zm5-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/><path fill-rule="evenodd" d="M13.5 5a.5.5 0 0 1 .5.5V7h1.5a.5.5 0 0 1 0 1H14v1.5a.5.5 0 0 1-1 0V8h-1.5a.5.5 0 0 1 0-1H13V5.5a.5.5 0 0 1 .5-.5z"/></svg></span>

                            Inscrit un nouveau étudiant

                        </h1><br>

                <form style="" id="form" method="post" enctype="multipart/form-data">

                                {% csrf_token %}
                                {{ form|crispy }}

                                <br><br>

                                <div class="form-group" style="margin: 10px; text-align: center">

                                    <button  class="btn btn-danger" type="submit">Valider l'inscription</button>

                                </div>
                                <br><br>


                            </form>



               </div>



            </div>


        </div>










    </div>







    </div>





{% endblock body %}

apps/templates/operations/modifier_enseignants.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

            {% include 'includes/menu_enseigants.html' %}


        </div>


        <div id="infos-etudiants">


            <br>
            <div id="cadre" style="overflow: scroll">


                <br>


                <div id="cadre-form2" style="width: 60%">

                    <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:details-enseignants' object.id %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>

                             <h1 id="titre-enregistrer">



                                 MODIFIER  - <span style=" color: red; font-weight: bold"> {{ object.prenom.upper }} {{ object.nom.upper }}</span>


                             </h1><br>






                   <form   class="form"  id="form" method="post" enctype="multipart/form-data">



                                {% csrf_token %}
                                {{ form|crispy }}

                                <br><br>
                                <div class="form-group" style="margin: 10px; text-align: center">

                                    <button  class="btn btn-danger" type="submit">Modifier</button>

                                </div><br><br>



                            </form>

                        </div>




            </div>


        </div>










    </div>







    </div>





{% endblock body %}

apps/templates/operations/modifier_etudiants.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">

            <br>


            <div id="cadre" style="overflow: scroll">


                <br>


                                    <div id="cadre-form2" style="width: 60%">

                                            <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:details-etudiants' object.id %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>

                             <h1 id="titre-enregistrer">



                                 MODIFIER  - <span style=" color: red; font-weight: bold"> {{ object.prenom.upper }} {{ object.nom.upper }}</span>


                             </h1><br>






                   <form   class="form"  id="form" method="post" enctype="multipart/form-data">



                                {% csrf_token %}
                                {{ form|crispy }}

                                <br><br> <br><br>

                                <div class="form-group" style="margin: 10px; text-align: center">

                                    <button  class="btn btn-danger" type="submit">Modifier</button>

                                </div>



                            </form>

                        </div>




            </div>


        </div>










    </div>







    </div>





{% endblock body %}

apps/templates/operations/modifier_inscriptions.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">


            <div id="cadre" style="overflow: auto">


                             <br>


                                    <div id="cadre-form2" style="width: 60%">

                                            <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:inscriptions' %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>

                             <h1 id="titre-enregistrer">



                                 MODIFIER  - <span style=" color: red; font-weight: bold"> {{ object.etudiant.prenom.upper }} {{ object.etudiant.nom.upper }}</span>


                             </h1><br>






                   <form   class="form"  id="form" method="post" enctype="multipart/form-data">



                                {% csrf_token %}
                                {{ form|crispy }}

                                <br><br>

                                <div class="form-group" style="margin: 10px; text-align: center">

                                    <button  class="btn btn-danger" type="submit">Modifier</button>

                                </div>



                            </form>

                        </div>





            </div>


        </div>










    </div>







    </div>





{% endblock body %}

apps/templates/operations/modifier_photo_enseignant.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">



            <div id="cadre">



                <br>
                <form style="text-align: center" id="form" method="post" enctype="multipart/form-data">

                     {% if enseignant.photo %}

                            <img id="img-modifier" src="{{ enseignant.photo.url }}"/> <br>

                        {% else %}

                            <img id="img-modifier" src="{% static 'apps/img/user.png' %}"/><br>

                        {% endif %}
                <br>


                                {% csrf_token %}
                                {{ form|crispy }}

                                <br><br>

                                <div class="form-group" style="margin: 10px; text-align: center">

                                    <a  class="btn btn-success" href="{% url 'apps:details-enseignants' enseignant.id %}" >Annuler</a>
                                    <button  class="btn btn-danger" type="submit">Modifier</button>

                                </div>
                                <br><br>


                            </form>




            </div>


        </div>










    </div>







    </div>





{% endblock body %}

apps/templates/operations/modifier_photo_etudiant.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">



            <div id="cadre">



                <br>
                <form style="text-align: center" id="form" method="post" enctype="multipart/form-data">

                     {% if etudiant.photo %}

                            <img id="img-modifier" src="{{ etudiant.photo.url }}"/> <br>

                        {% else %}

                            <img id="img-modifier" src="{% static 'apps/img/user.png' %}"/><br>

                        {% endif %}
                <br>


                                {% csrf_token %}
                                {{ form|crispy }}

                                <br><br>

                                <div class="form-group" style="margin: 10px; text-align: center">

                                    <a  class="btn btn-success" href="{% url 'apps:details-etudiants' etudiant.id %}" >Annuler</a>
                                    <button  class="btn btn-danger" type="submit">Modifier</button>

                                </div>
                                <br><br>


                            </form>




            </div>


        </div>










    </div>







    </div>





{% endblock body %}

apps/templates/operations/supprimer_enseignants.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

            {% include 'includes/menu_enseigants.html' %}


        </div>


        <div id="infos-etudiants">

            <br>


            <div id="cadre">


                <br>
                <div id="cadre-form2">


                                                      <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:details-enseignants' object.id %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>

                        <h1 id="titre-enregistrer">




                        SUPPRIMER - <span style="color: red">{{ object.prenom.upper  }} {{ object.nom.upper  }}</span>

                        </h1>
                        <br>

                        <form   class="form"  style="height: 260px" id="form" method="post" enctype="multipart/form-data">



                                {% csrf_token %}

                                  <fieldset class="form-group" style="margin: 10px; text-align: center">



                                <h2 style="font-size: 20px">Êtes-vous sur de vouloir supprimer cet enseignant ? <br>
                                    <p style="margin-top: 5px; font-size: 14px; color: red"> Il sera définitivement
                                        supprimer de la base de données. </p></h2>

                            </fieldset>


                                <br>

                                <div class="form-group" style="margin: 10px; text-align: center">

                                             <button  class="btn btn-danger" type="submit">Supprimer</button>

                                </div>
                                <br><br>



                            </form>

                            </div>




            </div>


        </div>










    </div>







    </div>






{% endblock body %}

apps/templates/operations/supprimer_etudiants.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">

            <br>

            <div id="cadre">


                <br>
                <div id="cadre-form2">


                    <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:details-etudiants' object.id %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>

                        <h1 id="titre-enregistrer">




                        SUPPRIMER - <span style="color: red">{{ object.prenom.upper  }} {{ object.nom.upper  }}</span>

                        </h1>
                        <br>

                        <form   class="form"  style="height: 260px" id="form" method="post" enctype="multipart/form-data">



                                {% csrf_token %}

                                  <fieldset class="form-group" style="margin: 10px; text-align: center">



                                <h2 style="font-size: 20px">Êtes-vous sur de vouloir supprimer cet étudiant ? <br>
                                    <p style="margin-top: 5px; font-size: 14px; color: red"> Il sera définitivement
                                        supprimer de la base de données. </p></h2>

                            </fieldset>


                                <br>

                                <div class="form-group" style="margin: 10px; text-align: center">

                                             <button  class="btn btn-danger" type="submit">Supprimer</button>

                                </div>
                                <br><br>



                            </form>

                            </div>




            </div>


        </div>










    </div>







    </div>





{% endblock body %}

apps/templates/operations/supprimer_inscriptions.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}



{% block body %}
    <div  id="container">


    <div id="cadre-etudiants">


        <div id="menu-etudiants">

           {% include 'includes/menu_etudiants.html' %}


        </div>


        <div id="infos-etudiants">



            <div id="cadre">



                           <br>
                        <div id="cadre-form2">


                                                      <div style="float: right;">

                      <a style="margin-left: -20px" href="{% url 'apps:inscriptions' %}">

                          <span>
                          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-x-square" viewBox="0 0 16 16">
                          <path d="M14 1a1 1 0 0 1 1 1v12a1 1 0 0 1-1 1H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                         <path d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"/>
                          </svg>
                          </span>



                      </a>


                   </div>

                        <h1 id="titre-enregistrer">




                        SUPPRIMER L'INSCRIPTION - <span style="color: red">{{ object.etudiant.prenom.upper  }} {{ object.etudiant.nom.upper  }}</span>

                        </h1>
                        <br>

                        <form   class="form"  style="height: 260px" id="form" method="post" enctype="multipart/form-data">



                                {% csrf_token %}

                                  <fieldset class="form-group" style="margin: 10px; text-align: center">



                                <h2 style="font-size: 20px">Êtes-vous sur de vouloir supprimer cette inscription ? <br>
                                    <p style="margin-top: 5px; font-size: 14px; color: red"> Elle sera définitivement
                                        supprimer de la base de données. </p></h2>

                            </fieldset>


                                <br>

                                <div class="form-group" style="margin: 10px; text-align: center">

                                             <button  class="btn btn-danger" type="submit">Supprimer</button>

                                </div>
                                <br><br>



                            </form>

                            </div>




            </div>


        </div>










    </div>







    </div>





{% endblock body %}